zabbix:
  server: https://server.zabbix
  credentials:
    username: zabbixapiuser
    password: password
  priority: 5
  hostid: 10000
app:
  env: dev
  credentials:
    username: servicedesk
    password: ZXCvbnm,.-2021