version: "3.2"
services: 
    sslchecker:
        build: 
          context: '.'
        container_name: sslchecker
        volumes: ['./:/app']
        restart: always
        ports: 
          - "8000:5000"