version: "3.2"
services: 
    sslchecker:
        build: 
          context: '.'
        container_name: sslchecker
        volumes: 
          - ./:/app
          - /etc/apache2/certificates/:/certs
        restart: always
        ports: 
          - "8000:5000"
        environment:
          - "PYTHONUNBUFFERED=1"